### ISSUE TITLE
[Feature Request]: Release spectre sweep support for lookup table generation

### ISSUE THREAD

**Issue by avlsi** [dreoilin/pygmid#14]
It would be a great feature to release spectre sweep support for lookup table generation. In addition, this could be extended to other simulators in future.

**Comment by dreoilin** [comment]
Thank you for the suggestion. Spectre characterisation will hopefully be added in a future update.

I don't have access to other simulators, but please feel free to contribute characterisation scripts for other simulators if you have them.

**Comment by dreoilin** [comment]
Parallel sweep processing has been added to the latest github version. You should be able to characterise a technology in about 1hr 30 mins compared to 8-12 for the Murmann sweep. Due to limitations with our test setup, we will not be adding support for other simulators. Please feel free to contribute if you can.

The sweep functionality is in beta and will change over the next week or so before a new version release. libpsf (an alternative psf parser) could be used to parse binaries from spectre and offer a slight speed increase. Unfortunately, we can't test with this package at the moment. Furthermore, if you have multiple cadence licenses, the sweep can be speed up by parallelising psf generation from spectre. This functionality has not been added to the script.

You can sweep a process with:

`python3 -m pygmid --mode sweep --config config.cfg`

A sample config file is given in tests/debug
